MLIR: lib/Conversion/AMDGPUToROCDL/AMDGPUToROCDL.cpp File Reference
AMDGPUToROCDL.cpp File Reference
#include "mlir/Conversion/AMDGPUToROCDL/AMDGPUToROCDL.h"
#include "../PassDetail.h"
#include "mlir/Conversion/LLVMCommon/ConversionTarget.h"
#include "mlir/Conversion/LLVMCommon/Pattern.h"
#include "mlir/Dialect/AMDGPU/AMDGPUDialect.h"
#include "mlir/Dialect/LLVMIR/ROCDLDialect.h"
Functions
static Value createI32Constant (ConversionPatternRewriter &rewriter, Location loc, int32_t value)
Function Documentation
createI32Constant()
static Value createI32Constant (ConversionPatternRewriter & rewriter, Location loc, int32_t value) static
Definition at line 18 of file AMDGPUToROCDL.cpp.
References mlir::ConversionTarget::addLegalDialect(), mlir::MemRefDescriptor::alignedPtr(), mlir::applyPartialConversion(), mlir::Type::cast(), mlir::OpBuilder::create(), mlir::Type::dyn_cast(), mlir::detail::enumerate(), mlir::ConversionPatternRewriter::eraseOp(), mlir::failed(), mlir::Builder::getI32IntegerAttr(), mlir::Builder::getI32Type(), mlir::Builder::getI64Type(), mlir::Builder::getIntegerType(), mlir::getStridesAndOffset(), mlir::Value::getType(), mlir::MemRefDescriptor::offset(), mlir::populateAMDGPUToROCDLConversionPatterns(), mlir::ConversionPatternRewriter::replaceOp(), mlir::MemRefDescriptor::size(), mlir::MemRefDescriptor::stride(), and mlir::success().