MLIR: mlir::transform::FunctionalStyleTransformOpTrait< OpTy > Class Template Reference
mlir::transform::FunctionalStyleTransformOpTrait< OpTy > Class Template Reference
Trait implementing the MemoryEffectOpInterface for single-operand single-result operations that "consume" their operand and produce a new result.
#include "mlir/Dialect/Transform/IR/TransformInterfaces.h"
Public Member Functions
void getEffects (SmallVectorImpl< MemoryEffects::EffectInstance > &effects)
This op "consumes" the operand by reading and freeing it, "produces" the result by allocating and writing it and reads/writes the payload IR in the process.
Static Public Member Functions
static LogicalResult verifyTrait (Operation *op)
Checks that the op matches the expectations of this trait.
Additional Inherited Members
Protected Member Functions inherited from mlir::OpTrait::TraitBase< OpTy, FunctionalStyleTransformOpTrait >
Operation * getOperation ()
Return the ultimate Operation being worked on.
Detailed Description
template<typename OpTy>
class mlir::transform::FunctionalStyleTransformOpTrait< OpTy >
Trait implementing the MemoryEffectOpInterface for single-operand single-result operations that "consume" their operand and produce a new result.
Definition at line 458 of file TransformInterfaces.h.
Member Function Documentation
getEffects()
template<typename OpTy > void mlir::transform::FunctionalStyleTransformOpTrait< OpTy >::getEffects (SmallVectorImpl< MemoryEffects::EffectInstance > & effects) inline
This op "consumes" the operand by reading and freeing it, "produces" the result by allocating and writing it and reads/writes the payload IR in the process.
Definition at line 464 of file TransformInterfaces.h.
References mlir::SideEffects::Effect::Base< DerivedEffect, BaseEffect >::get(), mlir::SideEffects::Resource::Base< PayloadIRResource >::get(), and mlir::SideEffects::Resource::Base< TransformMappingResource >::get().
verifyTrait()
template<typename OpTy > static LogicalResult mlir::transform::FunctionalStyleTransformOpTrait< OpTy >::verifyTrait (Operation * op) inline static
Checks that the op matches the expectations of this trait.
Definition at line 482 of file TransformInterfaces.h.
References mlir::Operation::emitError(), mlir::OperationName::getInterface(), mlir::Operation::getName(), mlir::success(), and value.
The documentation for this class was generated from the following file:
include/mlir/Dialect/Transform/IR/TransformInterfaces.h