MLIR: mlir::transform::TransformEachOpTrait< OpTy > Class Template Reference
mlir::transform::TransformEachOpTrait< OpTy > Class Template Reference
Trait implementing the TransformOpInterface for operations applying a transformation to a single operation handle and producing a single operation handle.
#include "mlir/Dialect/Transform/IR/TransformInterfaces.h"
Public Member Functions
LogicalResult apply (TransformResults &transformResults, TransformState &state)
Calls applyToOne for every payload operation associated with the operand of this transform IR op.
Static Public Member Functions
static LogicalResult verifyTrait (Operation *op)
Checks that the op matches the expectations of this trait.
Additional Inherited Members
Protected Member Functions inherited from mlir::OpTrait::TraitBase< OpTy, TransformEachOpTrait >
Operation * getOperation ()
Return the ultimate Operation being worked on.
Detailed Description
template<typename OpTy>
class mlir::transform::TransformEachOpTrait< OpTy >
Trait implementing the TransformOpInterface for operations applying a transformation to a single operation handle and producing a single operation handle.
The op must implement a method with one of the following signatures:
FailureOr<convertible-to-Operation*> applyToOne(OpTy)
LogicalResult applyToOne(OpTy) to perform a transformation that is applied in turn to all payload IR operations that correspond to the handle of the transform IR operation. In the functions above, OpTy is either Operation * or a concrete payload IR Op class that the transformation is applied to (NOT the class of the transform IR op). The op is expected to have one operand and zero or one results.
Definition at line 412 of file TransformInterfaces.h.
Member Function Documentation
apply()
template<typename OpTy > mlir::LogicalResult mlir::transform::TransformEachOpTrait< OpTy >::apply (TransformResults & transformResults, TransformState & state)
Calls applyToOne for every payload operation associated with the operand of this transform IR op.
If applyToOne returns ops, associates them with the result of this transform op.
Definition at line 565 of file TransformInterfaces.h.
References mlir::transform::detail::applyTransformToEach(), mlir::failed(), mlir::failure(), mlir::transform::TransformState::getPayloadOps(), mlir::transform::TransformResults::set(), and mlir::success().
verifyTrait()
template<typename OpTy > mlir::LogicalResult mlir::transform::TransformEachOpTrait< OpTy >::verifyTrait (Operation * op) static
Checks that the op matches the expectations of this trait.
Definition at line 586 of file TransformInterfaces.h.
References mlir::Operation::emitError(), mlir::OperationName::getInterface(), mlir::Operation::getName(), and mlir::success().
The documentation for this class was generated from the following file:
include/mlir/Dialect/Transform/IR/TransformInterfaces.h