MLIR: lib/Dialect/Math/Transforms/ExpandPatterns.cpp File Reference
ExpandPatterns.cpp File Reference
#include "mlir/Dialect/Arithmetic/IR/Arithmetic.h"
#include "mlir/Dialect/Math/IR/Math.h"
#include "mlir/Dialect/Math/Transforms/Passes.h"
#include "mlir/Dialect/SCF/SCF.h"
#include "mlir/IR/Builders.h"
#include "mlir/Transforms/DialectConversion.h"
Functions
static LogicalResult convertTanhOp (math::TanhOp op, PatternRewriter &rewriter)
Expands tanh op into 1) 1-exp^{-2x} / 1+exp^{-2x}, if x => 0 2) exp^{2x}-1 / exp^{2x}+1 , if x < 0.
static LogicalResult convertCtlzOp (math::CountLeadingZerosOp op, PatternRewriter &rewriter)
Function Documentation
convertCtlzOp()
static LogicalResult convertCtlzOp (math::CountLeadingZerosOp op, PatternRewriter & rewriter) static
Definition at line 57 of file ExpandPatterns.cpp.
References mlir::OpBuilder::create(), mlir::OpBuilder::createBlock(), mlir::Block::getArgument(), mlir::RewriterBase::replaceOp(), mlir::OpBuilder::setInsertionPointAfter(), mlir::OpBuilder::setInsertionPointToStart(), and mlir::success().
Referenced by mlir::populateExpandCtlzPattern().
convertTanhOp()
static LogicalResult convertTanhOp (math::TanhOp op, PatternRewriter & rewriter) static
Expands tanh op into 1) 1-exp^{-2x} / 1+exp^{-2x}, if x => 0 2) exp^{2x}-1 / exp^{2x}+1 , if x < 0.
Definition at line 25 of file ExpandPatterns.cpp.
References mlir::OpBuilder::create(), mlir::Builder::getFloatAttr(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().
Referenced by mlir::populateExpandTanhPattern().