MLIR: lib/Dialect/Linalg/TransformOps/LinalgTransformOps.cpp File Reference
LinalgTransformOps.cpp File Reference
#include "mlir/Dialect/Linalg/TransformOps/LinalgTransformOps.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/PDL/IR/PDL.h"
#include "mlir/Dialect/PDL/IR/PDLTypes.h"
#include "mlir/Dialect/Transform/IR/TransformDialect.h"
#include "mlir/Interfaces/SideEffectInterfaces.h"
#include "mlir/Parser/Parser.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "llvm/Support/FormatVariadic.h"
#include "mlir/Dialect/Linalg/TransformOps/LinalgTransformOps.cpp.inc"
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
static SmallVector< int64_t > extractI64Array (ArrayAttr attr)
Extracts a vector of int64_t from an array attribute.
static SmallVector< unsigned > extractUIntArray (ArrayAttr attr)
Extracts a vector of unsigned from an array attribute.
template<typename PatternTy , typename... Args>
static FailureOr< LinalgOp > tryApply (Operation *operation, Args &&...args)
Attempts to apply the pattern specified as template argument to the given operation.
static LogicalResult applyTilingToAll (Operation *transformOp, Value target, ArrayRef< int64_t > tileSizes, transform::TransformResults &transformResults, transform::TransformState &state, function_ref< FailureOr< TiledLinalgOp >(LinalgOp)> applyFn)
Apply a tiling transformation to all payload ops and store both the tiled operation as well as the created tile loops.
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 450 of file LinalgTransformOps.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
applyTilingToAll()
static LogicalResult applyTilingToAll (Operation * transformOp, Value target, ArrayRef< int64_t > tileSizes, transform::TransformResults & transformResults, transform::TransformState & state, function_ref< FailureOr< TiledLinalgOp >(LinalgOp)> applyFn) static
Apply a tiling transformation to all payload ops and store both the tiled operation as well as the created tile loops.
Definition at line 284 of file LinalgTransformOps.cpp.
References mlir::RewritePatternSet::add(), mlir::OperationState::addTypes(), mlir::applyPatternsAndFoldGreedily(), mlir::InFlightDiagnostic::attachNote(), mlir::OperationState::attributes, diag(), mlir::Attribute::dyn_cast(), mlir::AsmParser::emitError(), mlir::emitError(), mlir::Operation::emitError(), extractI64Array(), extractUIntArray(), mlir::failed(), mlir::failure(), mlir::SideEffects::Effect::Base< DerivedEffect, BaseEffect >::get(), mlir::NamedAttrList::get(), mlir::AsmParser::getBuilder(), mlir::AsmParser::getCurrentLocation(), mlir::Operation::getLoc(), mlir::Operation::getOpResult(), mlir::transform::TransformState::getPayloadOps(), mlir::Builder::getType(), mlir::Operation::hasTrait(), mlir::OperationState::name, mlir::OperationState::operands, mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalAttrDict(), mlir::linalg::populatePadOpVectorizationPatterns(), mlir::vector::populateVectorReductionToContractPatterns(), mlir::vector::populateVectorTransferPermutationMapLoweringPatterns(), print(), mlir::OpAsmPrinter::printOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), mlir::linalg::LinalgTilingPattern::returningMatchAndRewrite(), mlir::transform::TransformResults::set(), mlir::linalg::LinalgTilingOptions::setInterchange(), mlir::linalg::LinalgTilingOptions::setTileSizes(), and mlir::success().
extractI64Array()
static SmallVector<int64_t> extractI64Array (ArrayAttr attr) static
Extracts a vector of int64_t from an array attribute.
Asserts if the attribute contains values other than integers.
Definition at line 27 of file LinalgTransformOps.cpp.
References value.
Referenced by applyTilingToAll(), and tryApply().
extractUIntArray()
static SmallVector<unsigned> extractUIntArray (ArrayAttr attr) static
Extracts a vector of unsigned from an array attribute.
Asserts if the attribute contains values other than intergers. May truncate.
Definition at line 37 of file LinalgTransformOps.cpp.
References value.
Referenced by applyTilingToAll(), and tryApply().
tryApply()
template<typename PatternTy , typename... Args> static FailureOr<LinalgOp> tryApply (Operation * operation, Args &&... args) static
Attempts to apply the pattern specified as template argument to the given operation.
The pattern is expected to have a returningMatchAndRewrite function that returns the "main" result or failure. Returns failure if the pattern failed to apply. Extra arguments are forwarded to the pattern constructor.
Definition at line 59 of file LinalgTransformOps.cpp.
References mlir::InFlightDiagnostic::attachNote(), mlir::Attribute::cast(), diag(), mlir::Attribute::dyn_cast(), mlir::emitError(), mlir::extractFromI64ArrayAttr(), extractI64Array(), extractUIntArray(), mlir::failed(), mlir::failure(), mlir::Operation::getContext(), mlir::getElementTypeOrSelf(), mlir::Attribute::getType(), mlir::parseAttribute(), mlir::linalg::LinalgTilingPattern::returningMatchAndRewrite(), mlir::linalg::LinalgTilingOptions::scalarizeDynamicDims(), mlir::linalg::LinalgPaddingOptions::setHoistPaddings(), mlir::linalg::LinalgPaddingOptions::setPackPaddings(), mlir::linalg::LinalgPaddingOptions::setPaddingDimensions(), mlir::linalg::LinalgPaddingOptions::setPaddingValues(), mlir::linalg::LinalgPaddingOptions::setTransposePaddings(), mlir::succeeded(), mlir::success(), and mlir::verify().