MLIR: lib/Dialect/MLProgram/IR/MLProgramOps.cpp File Reference
MLProgramOps.cpp File Reference
#include "mlir/Dialect/MLProgram/IR/MLProgram.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/FunctionImplementation.h"
#include "mlir/Dialect/MLProgram/IR/MLProgramOps.cpp.inc"
Macros
#define GET_OP_CLASSES
Functions
static ParseResult parseTokenOrdering (OpAsmParser &parser, SmallVectorImpl< OpAsmParser::UnresolvedOperand > &consumeTokens, Type &produceTokenType)
Parse and print an ordering clause for a variadic of consuming tokens and an optional producing token.
static void printTokenOrdering (OpAsmPrinter &p, Operation *op, OperandRange consumeTokens, Type produceTokenType)
static ParseResult parseTypedInitialValue (OpAsmParser &parser, TypeAttr &typeAttr, Attribute &attr)
some.op custom<TypeOrAttr>($type, $attr)
static void printTypedInitialValue (OpAsmPrinter &p, Operation *op, TypeAttr type, Attribute attr)
static ParseResult parseSymbolVisibility (OpAsmParser &parser, StringAttr &symVisibilityAttr)
some.op custom<SymbolVisibility>($sym_visibility) $sym_name -> some.op public some.op private
static void printSymbolVisibility (OpAsmPrinter &p, Operation *op, StringAttr symVisibilityAttr)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 141 of file MLProgramOps.cpp.
Function Documentation
parseSymbolVisibility()
static ParseResult parseSymbolVisibility (OpAsmParser & parser, StringAttr & symVisibilityAttr) static
some.op custom<SymbolVisibility>($sym_visibility) $sym_name -> some.op public some.op private
Definition at line 116 of file MLProgramOps.cpp.
References mlir::AsmParser::emitError(), mlir::AsmParser::getBuilder(), mlir::AsmParser::getCurrentLocation(), mlir::Builder::getStringAttr(), mlir::AsmParser::parseOptionalKeyword(), and mlir::success().
parseTokenOrdering()
static ParseResult parseTokenOrdering (OpAsmParser & parser, SmallVectorImpl< OpAsmParser::UnresolvedOperand > & consumeTokens, Type & produceTokenType) static
Parse and print an ordering clause for a variadic of consuming tokens and an optional producing token.
Syntax: ordering(%0, %1 -> !ml_program.token) ordering(() -> !ml_program.token) ordering(%0, %1)
If both the consuming and producing token are not present on the op, then the clause prints nothing.
Definition at line 30 of file MLProgramOps.cpp.
References mlir::failed(), mlir::failure(), mlir::AsmParser::parseLParen(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseOptionalArrow(), mlir::AsmParser::parseOptionalKeyword(), mlir::AsmParser::parseOptionalLParen(), mlir::AsmParser::parseRParen(), mlir::AsmParser::parseType(), mlir::succeeded(), and mlir::success().
parseTypedInitialValue()
static ParseResult parseTypedInitialValue (OpAsmParser & parser, TypeAttr & typeAttr, Attribute & attr) static
some.op custom<TypeOrAttr>($type, $attr)
Uninitialized: some.op : tensor<3xi32> Initialized to narrower type than op: some.op (dense<0> : tensor<3xi32>) : tensor<?xi32>
Definition at line 84 of file MLProgramOps.cpp.
References mlir::failed(), mlir::failure(), mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseColonType(), mlir::AsmParser::parseOptionalLParen(), mlir::AsmParser::parseRParen(), mlir::succeeded(), and mlir::success().
printSymbolVisibility()
static void printSymbolVisibility (OpAsmPrinter & p, Operation * op, StringAttr symVisibilityAttr) static
Definition at line 129 of file MLProgramOps.cpp.
printTokenOrdering()
static void printTokenOrdering (OpAsmPrinter & p, Operation * op, OperandRange consumeTokens, Type produceTokenType) static
Definition at line 60 of file MLProgramOps.cpp.
References mlir::OpAsmPrinter::printOperands(), and mlir::AsmPrinter::printType().
printTypedInitialValue()
static void printTypedInitialValue (OpAsmPrinter & p, Operation * op, TypeAttr type, Attribute attr) static
Definition at line 100 of file MLProgramOps.cpp.
References mlir::AsmPrinter::printAttribute().