MLIR: mlir::transform::detail Namespace Reference
mlir::transform::detail Namespace Reference
Functions
template<typename OpTy >
static void checkImplementsTransformInterface (MLIRContext *context)
Asserts that the operations provided as template arguments implement the TransformOpInterface and MemoryEffectsOpInterface.
LogicalResult mapPossibleTopLevelTransformOpBlockArguments (TransformState &state, Operation *op)
Maps the only block argument of the op with PossibleTopLevelTransformOpTrait to either the list of operations associated with its operand or the root of the payload IR, depending on what is available in the context.
LogicalResult verifyPossibleTopLevelTransformOpTrait (Operation *op)
Verification hook for PossibleTopLevelTransformOpTrait.
template<typename Ty >
std::enable_if_t< std::is_same< Ty, LogicalResult >::value, LogicalResult > appendTransformResultToVector (Ty result, SmallVectorImpl< Operation *> &results)
Appends result to the vector assuming it corresponds to the success state in FailureOr<convertible-to-Operation*>.
template<typename Ty >
std::enable_if_t<!std::is_same< Ty, LogicalResult >::value, LogicalResult > appendTransformResultToVector (Ty result, SmallVectorImpl< Operation *> &results)
template<typename FnTy >
LogicalResult applyTransformToEach (ArrayRef< Operation *> targets, SmallVectorImpl< Operation *> &results, FnTy transform)
Applies a one-to-one transform to each of the given targets.
Function Documentation
appendTransformResultToVector() [1/2]
template<typename Ty > std::enable_if_t<std::is_same<Ty, LogicalResult>::value, LogicalResult> mlir::transform::detail::appendTransformResultToVector (Ty result, SmallVectorImpl< Operation *> & results)
Appends result to the vector assuming it corresponds to the success state in FailureOr<convertible-to-Operation*>.
If result is just a LogicalResult, does nothing.
Definition at line 509 of file TransformInterfaces.h.
References value.
appendTransformResultToVector() [2/2]
template<typename Ty > std::enable_if_t<!std::is_same<Ty, LogicalResult>::value, LogicalResult> mlir::transform::detail::appendTransformResultToVector (Ty result, SmallVectorImpl< Operation *> & results)
Definition at line 515 of file TransformInterfaces.h.
References mlir::failed(), mlir::failure(), mlir::success(), and value.
Referenced by applyTransformToEach().
applyTransformToEach()
template<typename FnTy > LogicalResult mlir::transform::detail::applyTransformToEach (ArrayRef< Operation *> targets, SmallVectorImpl< Operation *> & results, FnTy transform)
Applies a one-to-one transform to each of the given targets.
Puts the results of transforms, if any, in results in the same order. Fails if any of the application fails. Individual transforms must be callable with one of the following signatures:
FailureOr<convertible-to-Operation*>(OpTy)
LogicalResult(OpTy) where OpTy is either
Operation *, in which case the transform is always applied;
a concrete Op class, in which case a check is performed whether targets contains operations of the same class and a failure is reported if it does not.
Definition at line 539 of file TransformInterfaces.h.
References appendTransformResultToVector(), mlir::failed(), mlir::failure(), mlir::success(), and value.
Referenced by mlir::transform::TransformEachOpTrait< OpTy >::apply().
checkImplementsTransformInterface()
template<typename OpTy > static void mlir::transform::detail::checkImplementsTransformInterface (MLIRContext * context) inline static
Asserts that the operations provided as template arguments implement the TransformOpInterface and MemoryEffectsOpInterface.
This must be a dynamic assertion since interface implementations may be registered at runtime.
Definition at line 26 of file TransformDialect.h.
References mlir::OperationName::hasInterface(), mlir::RegisteredOperationName::hasTrait(), and mlir::RegisteredOperationName::lookup().
mapPossibleTopLevelTransformOpBlockArguments()
LogicalResult mlir::transform::detail::mapPossibleTopLevelTransformOpBlockArguments (TransformState & state, Operation * op)
Maps the only block argument of the op with PossibleTopLevelTransformOpTrait to either the list of operations associated with its operand or the root of the payload IR, depending on what is available in the context.
Definition at line 204 of file TransformInterfaces.cpp.
References mlir::Region::front(), mlir::Block::getArgument(), mlir::Operation::getNumOperands(), mlir::Operation::getOperand(), mlir::transform::TransformState::getPayloadOps(), mlir::Operation::getRegion(), mlir::transform::TransformState::getTopLevel(), and mlir::transform::TransformState::mapBlockArguments().
Referenced by mlir::transform::TransformState::make_region_scope(), and mlir::transform::PossibleTopLevelTransformOpTrait< OpTy >::mapBlockArguments().
verifyPossibleTopLevelTransformOpTrait()
LogicalResult mlir::transform::detail::verifyPossibleTopLevelTransformOpTrait (Operation * op)
Verification hook for PossibleTopLevelTransformOpTrait.
Definition at line 217 of file TransformInterfaces.cpp.
References mlir::InFlightDiagnostic::attachNote(), diag(), mlir::Operation::emitOpError(), mlir::Region::front(), mlir::Block::getArgumentTypes(), mlir::Operation::getContext(), mlir::Block::getNumArguments(), mlir::Operation::getNumOperands(), mlir::Operation::getNumRegions(), mlir::Operation::getParentWithTrait(), mlir::Operation::getRegion(), and mlir::success().
Referenced by mlir::transform::TransformState::make_region_scope(), and mlir::transform::PossibleTopLevelTransformOpTrait< OpTy >::verifyTrait().