MLIR: mlir::nvgpu Namespace Reference
mlir::nvgpu Namespace Reference
Classes
class DeviceAsyncTokenType
Device-side token storage type. There is only one type of device-side token.
struct FragmentElementInfo
Specifies information about the registers which compose a matrix fragment according to the PTX documentation.
struct LdMatrixParams
struct PrepareContractToGPUMMASync
struct WarpMatrixInfo
Collects information about a warp-level matrix operand represented by a VectorType.
Enumerations
enum MatMulOperandRole : int32_t { MatMulOperandRole::A = 0, MatMulOperandRole::B, MatMulOperandRole::C }
Functions
FailureOr< WarpMatrixInfo > getWarpMatrixInfo (Operation *op)
Given an op that operates on a VectorType representing a warp-level matrix operand, the function returns a struct containing relevant type information.
int64_t inferTileWidthInBits (const WarpMatrixInfo &type)
Returns the number of bits in a single tile row.
FailureOr< FragmentElementInfo > getMmaSyncRegisterType (const WarpMatrixInfo &type)
Returns a FragmentElementInfo struct describing the register types for the given matrix fragment type.
static AffineMap getRegisterIndexToTileOffsetMap (int64_t lineSize, Type elementType, ArrayRef< int64_t > operandShape, bool isAccumulator, int64_t elementsPerRegister, AffineExpr logicalValueId)
FailureOr< AffineMap > getLaneIdAndValueIdToOperandCoord (Location loc, OpBuilder &builder, const WarpMatrixInfo &fragmentType)
Returns an AffineMap which maps a two dimensions representing (laneId, logicalValueId) and returns two results representing offsets within a matrix operand.
FailureOr< nvgpu::LdMatrixParams > getLdMatrixParams (const WarpMatrixInfo &type, bool transpose)
FailureOr< AffineMap > getLaneIdToLdMatrixMatrixCoord (Location loc, OpBuilder &builder, const LdMatrixParams &params)
Returns an AffineMap which maps a single dimension representing the laneId to two results representing offsets within the matrix operand that should be the pointer locations a thread should pass to the ldmatrix instruction.
Enumeration Type Documentation
MatMulOperandRole
enum mlir::nvgpu::MatMulOperandRole : int32_t strong
Enumerator
A
B
C
Definition at line 27 of file NvGpuSupport.h.
Function Documentation
getLaneIdAndValueIdToOperandCoord()
FailureOr< AffineMap > mlir::nvgpu::getLaneIdAndValueIdToOperandCoord (Location loc, OpBuilder & builder, const WarpMatrixInfo & fragmentType)
Returns an AffineMap which maps a two dimensions representing (laneId, logicalValueId) and returns two results representing offsets within a matrix operand.
The offsets point to the values the thread is responsible for (AKA the matrix fragment values) during a warp-collective matrix operation. For a visual reference of this LaneId -> (row, col) mapping, please see NVIDIA's PTX documentation: https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#warp-level-matrix-instructions-for-mma
Definition at line 165 of file NvGpuSupport.cpp.
References mlir::bindDims(), mlir::failed(), mlir::failure(), mlir::AffineExpr::floorDiv(), mlir::AffineMap::get(), mlir::Builder::getContext(), mlir::Type::getIntOrFloatBitWidth(), getMmaSyncRegisterType(), getRegisterIndexToTileOffsetMap(), mlir::AffineMap::getResult(), inferTileWidthInBits(), mlir::nvgpu::WarpMatrixInfo::operandRole, and mlir::nvgpu::WarpMatrixInfo::vectorType.
Referenced by convertTransferWriteToStores(), and createNonLdMatrixLoads().
getLaneIdToLdMatrixMatrixCoord()
FailureOr< AffineMap > mlir::nvgpu::getLaneIdToLdMatrixMatrixCoord (Location loc, OpBuilder & builder, const LdMatrixParams & params)
Returns an AffineMap which maps a single dimension representing the laneId to two results representing offsets within the matrix operand that should be the pointer locations a thread should pass to the ldmatrix instruction.
Definition at line 230 of file NvGpuSupport.cpp.
References mlir::nvgpu::LdMatrixParams::contiguousDimType, mlir::failure(), mlir::AffineExpr::floorDiv(), mlir::nvgpu::LdMatrixParams::fragmentType, mlir::AffineMap::get(), mlir::getAffineDimExpr(), mlir::Builder::getContext(), mlir::Parallel, and mlir::Reduction.
Referenced by creatLdMatrixCompatibleLoads().
getLdMatrixParams()
FailureOr< LdMatrixParams > mlir::nvgpu::getLdMatrixParams (const WarpMatrixInfo & type, bool transpose)
Definition at line 200 of file NvGpuSupport.cpp.
References A, C, mlir::nvgpu::LdMatrixParams::contiguousDimType, mlir::failure(), mlir::nvgpu::LdMatrixParams::fragmentType, mlir::Type::getIntOrFloatBitWidth(), mlir::nvgpu::LdMatrixParams::numTiles, mlir::nvgpu::WarpMatrixInfo::operandRole, mlir::Parallel, mlir::Reduction, mlir::nvgpu::LdMatrixParams::targetLayout, and mlir::nvgpu::WarpMatrixInfo::vectorType.
Referenced by creatLdMatrixCompatibleLoads().
getMmaSyncRegisterType()
FailureOr< FragmentElementInfo > mlir::nvgpu::getMmaSyncRegisterType (const WarpMatrixInfo & type)
Returns a FragmentElementInfo struct describing the register types for the given matrix fragment type.
Definition at line 100 of file NvGpuSupport.cpp.
References mlir::failure(), mlir::LLVM::getFixedVectorType(), mlir::Type::isF16(), mlir::Type::isF32(), mlir::Type::isF64(), mlir::Type::isInteger(), mlir::nvgpu::WarpMatrixInfo::operandRole, and mlir::nvgpu::WarpMatrixInfo::vectorType.
Referenced by convertConstantOpMmaSync(), convertTransferWriteToStores(), createNonLdMatrixLoads(), creatLdMatrixCompatibleLoads(), and getLaneIdAndValueIdToOperandCoord().
getRegisterIndexToTileOffsetMap()
static AffineMap mlir::nvgpu::getRegisterIndexToTileOffsetMap (int64_t lineSize, Type elementType, ArrayRef< int64_t > operandShape, bool isAccumulator, int64_t elementsPerRegister, AffineExpr logicalValueId) static
Definition at line 146 of file NvGpuSupport.cpp.
References mlir::AffineExpr::floorDiv(), mlir::AffineMap::get(), mlir::Type::getContext(), and mlir::Type::getIntOrFloatBitWidth().
Referenced by getLaneIdAndValueIdToOperandCoord().
getWarpMatrixInfo()
FailureOr< WarpMatrixInfo > mlir::nvgpu::getWarpMatrixInfo (Operation * op)
Given an op that operates on a VectorType representing a warp-level matrix operand, the function returns a struct containing relevant type information.
Definition at line 54 of file NvGpuSupport.cpp.
References A, B, C, mlir::Type::cast(), contract(), mlir::Operation::emitError(), mlir::Operation::getResult(), mlir::Value::getType(), mlir::Operation::getUsers(), mlir::nvgpu::WarpMatrixInfo::operandRole, and mlir::nvgpu::WarpMatrixInfo::vectorType.
Referenced by convertConstantOpMmaSync(), convertTransferReadToLoads(), convertTransferWriteToStores(), createNonLdMatrixLoads(), and creatLdMatrixCompatibleLoads().
inferTileWidthInBits()
int64_t mlir::nvgpu::inferTileWidthInBits (const WarpMatrixInfo & type)
Returns the number of bits in a single tile row.
It is either 128, 256, or 512 bits depending on the data type and` whether the operand is an accumulator/result operand
Definition at line 87 of file NvGpuSupport.cpp.
References mlir::Type::getIntOrFloatBitWidth(), mlir::nvgpu::WarpMatrixInfo::operandRole, and mlir::nvgpu::WarpMatrixInfo::vectorType.
Referenced by convertTransferReadToLoads(), and getLaneIdAndValueIdToOperandCoord().