MLIR: lib/Dialect/NVGPU/IR/NVGPUDialect.cpp File Reference
NVGPUDialect.cpp File Reference
#include "mlir/Dialect/NVGPU/NVGPUDialect.h"
#include "mlir/Dialect/GPU/GPUDialect.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/TypeUtilities.h"
#include "llvm/ADT/TypeSwitch.h"
#include "mlir/Dialect/NVGPU/NVGPUDialect.cpp.inc"
#include "mlir/Dialect/NVGPU/NVGPU.cpp.inc"
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
static bool isLastMemrefDimUnitStride (MemRefType type)
Return true if the last dimension of the MemRefType has unit stride.
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 90 of file NVGPUDialect.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
isLastMemrefDimUnitStride()
static bool isLastMemrefDimUnitStride (MemRefType type) static
Return true if the last dimension of the MemRefType has unit stride.
Also return true for memrefs with no strides.
Definition at line 59 of file NVGPUDialect.cpp.
References mlir::emitError(), mlir::failed(), mlir::getStridesAndOffset(), mlir::success(), and mlir::verify().