MLIR: lib/Dialect/Vector/Transforms/VectorDistribute.cpp File Reference
VectorDistribute.cpp File Reference
#include "mlir/Dialect/Arithmetic/IR/Arithmetic.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/SCF.h"
#include "mlir/Dialect/Vector/Transforms/VectorDistribution.h"
Functions
static LogicalResult rewriteWarpOpToScfFor (RewriterBase &rewriter, WarpExecuteOnLane0Op warpOp, const WarpExecuteOnLane0LoweringOptions &options)
Function Documentation
rewriteWarpOpToScfFor()
static LogicalResult rewriteWarpOpToScfFor (RewriterBase & rewriter, WarpExecuteOnLane0Op warpOp, const WarpExecuteOnLane0LoweringOptions & options) static
Definition at line 18 of file VectorDistribute.cpp.
References mlir::Type::cast(), mlir::OpBuilder::create(), mlir::detail::enumerate(), mlir::RewriterBase::eraseOp(), mlir::Block::front(), mlir::Value::getType(), mlir::Type::isa(), mlir::RewriterBase::mergeBlocks(), options, mlir::RewriterBase::replaceOp(), mlir::OpBuilder::setInsertionPoint(), mlir::OpBuilder::setInsertionPointAfter(), mlir::OpBuilder::setInsertionPointToEnd(), mlir::OpBuilder::setInsertionPointToStart(), mlir::success(), vectorType(), mlir::vector::WarpExecuteOnLane0LoweringOptions::warpAllocationFn, and mlir::vector::WarpExecuteOnLane0LoweringOptions::warpSyncronizationFn.